### ISSUE TITLE
opening in microchip studio

### ISSUE THREAD

**Issue by danyUt5** [microchip-pic-avr-examples/avr128db48-opamp-gain-and-offset-calibration#1]
Hi,

I am having trouble openning this program in microchip studio. It wants it set up as an (.atzip) file instead of a (.zip) file. any suggestions on how to set that up?

**Comment by Dradnats** [comment]
Hi @danyUt5,

 I assume you are clicking on the "Code" button and "Download Zip".

![image](https://user-images.githubusercontent.com/10521946/145555766-b162a070-251b-4b7c-8b0a-9505479befcc.png)

If so, you are getting the zipped GitHub structure, and not a Studio .atzip file. 

Recommend you unzip the file, and then open the .atsln file in Microchip Studio.

Hope this helps. :)

**Comment by pic-avr-github-admin** [comment]
Closing this issue as no follow-up questions were asked.
